"""Add PropertyShapeData EAV table

Revision ID: 0cc3a3477533
Revises: 9b875f2af7b4
Create Date: 2026-03-06 04:53:08.253955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc3a3477533'
down_revision: Union[str, None] = '9b875f2af7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_shape_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('subcategory', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'category', 'subcategory', name='uq_property_shape_data_cat_subcat')
    )
    op.create_index(op.f('ix_property_shape_data_category'), 'property_shape_data', ['category'], unique=False)
    op.create_index(op.f('ix_property_shape_data_id'), 'property_shape_data', ['id'], unique=False)
    op.create_index(op.f('ix_property_shape_data_property_id'), 'property_shape_data', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_shape_data_property_id'), table_name='property_shape_data')
    op.drop_index(op.f('ix_property_shape_data_id'), table_name='property_shape_data')
    op.drop_index(op.f('ix_property_shape_data_category'), table_name='property_shape_data')
    op.drop_table('property_shape_data')
    # ### end Alembic commands ###
