"""sync_schema

Revision ID: 16d27a17105f
Revises: ab8d09ddfbb1
Create Date: 2026-02-19 04:51:38.654772

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.engine.reflection import Inspector
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '16d27a17105f'
down_revision: Union[str, None] = 'ab8d09ddfbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'auction_events' not in tables:
        op.create_table('auction_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('short_name', sa.String(length=100), nullable=True),
        sa.Column('auction_date', sa.Date(), nullable=False),
        sa.Column('time', sa.String(length=50), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('county', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('search_link', sa.String(length=500), nullable=True),
        sa.Column('register_date', sa.Date(), nullable=True),
        sa.Column('register_link', sa.String(length=500), nullable=True),
        sa.Column('list_link', sa.String(length=500), nullable=True),
        sa.Column('purchase_info_link', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('auction_events', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_auction_events_id'), ['id'], unique=False)

    if 'inventory_folders' not in tables:
        op.create_table('inventory_folders',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('parent_id', sa.String(length=36), nullable=True),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('is_system', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.ForeignKeyConstraint(['parent_id'], ['inventory_folders.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('inventory_folders', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_inventory_folders_company_id'), ['company_id'], unique=False)

    if 'properties' not in tables:
        op.create_table('properties',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('address', sa.String(length=255), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('zip_code', sa.String(length=20), nullable=True),
        sa.Column('county', sa.String(length=100), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('property_type', sa.String(length=50), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('parcel_id', sa.String(length=100), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('smart_tag', sa.String(length=50), nullable=True),
        sa.Column('local_id', sa.Integer(), autoincrement=True, nullable=True),
        sa.Column('owner_name', sa.String(length=255), nullable=True),
        sa.Column('owner_address', sa.String(length=255), nullable=True),
        sa.Column('amount_due', sa.Float(), nullable=True),
        sa.Column('next_auction_date', sa.Date(), nullable=True),
        sa.Column('occupancy', sa.String(length=50), nullable=True),
        sa.Column('tax_sale_year', sa.Integer(), nullable=True),
        sa.Column('cs_number', sa.String(length=100), nullable=True),
        sa.Column('parcel_code', sa.String(length=100), nullable=True),
        sa.Column('map_link', sa.String(length=500), nullable=True),
        sa.Column('company_id', sa.Integer(), nullable=True),
        sa.Column('auction_event_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['auction_event_id'], ['auction_events.id'], ),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('local_id')
        )
        with op.batch_alter_table('properties', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_properties_auction_event_id'), ['auction_event_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_properties_city'), ['city'], unique=False)
            batch_op.create_index(batch_op.f('ix_properties_company_id'), ['company_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_properties_county'), ['county'], unique=False)
            batch_op.create_index(batch_op.f('ix_properties_parcel_id'), ['parcel_id'], unique=True)
            batch_op.create_index(batch_op.f('ix_properties_smart_tag'), ['smart_tag'], unique=True)
            batch_op.create_index(batch_op.f('ix_properties_state'), ['state'], unique=False)
            batch_op.create_index(batch_op.f('ix_properties_zip_code'), ['zip_code'], unique=False)

    if 'user_company' not in tables:
        op.create_table('user_company',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'company_id')
        )
    if 'auction_details' not in tables:
        op.create_table('auction_details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.String(length=36), nullable=False),
        sa.Column('auction_date', sa.Date(), nullable=True),
        sa.Column('auction_start', sa.DateTime(), nullable=True),
        sa.Column('auction_end', sa.DateTime(), nullable=True),
        sa.Column('reserve_price', sa.Float(), nullable=True),
        sa.Column('scraped_file', sa.String(length=255), nullable=True),
        sa.Column('status_detail', sa.String(length=255), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('sold_to', sa.String(length=255), nullable=True),
        sa.Column('auction_type', sa.String(length=100), nullable=True),
        sa.Column('case_number', sa.String(length=100), nullable=True),
        sa.Column('certificate_number', sa.String(length=100), nullable=True),
        sa.Column('opening_bid', sa.Float(), nullable=True),
        sa.Column('raw_text', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('property_id')
        )
        with op.batch_alter_table('auction_details', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_auction_details_case_number'), ['case_number'], unique=False)
            batch_op.create_index(batch_op.f('ix_auction_details_id'), ['id'], unique=False)

    if 'expenses' not in tables:
        op.create_table('expenses',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('property_id', sa.String(length=36), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'inventory_items' not in tables:
        op.create_table('inventory_items',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('folder_id', sa.String(length=36), nullable=True),
        sa.Column('property_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('user_notes', sa.Text(), nullable=True),
        sa.Column('tags', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.ForeignKeyConstraint(['folder_id'], ['inventory_folders.id'], ),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('inventory_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_inventory_items_company_id'), ['company_id'], unique=False)

    if 'media' not in tables:
        op.create_table('media',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.String(length=36), nullable=False),
        sa.Column('media_type', sa.String(length=50), nullable=True),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('media', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_media_id'), ['id'], unique=False)

    if 'notes' not in tables:
        op.create_table('notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('notes', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_notes_property_id'), ['property_id'], unique=False)

    if 'property_auction_history' not in tables:
        op.create_table('property_auction_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.String(length=36), nullable=False),
        sa.Column('auction_name', sa.String(length=255), nullable=True),
        sa.Column('auction_date', sa.Date(), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('listed_as', sa.String(length=255), nullable=True),
        sa.Column('taxes_due', sa.Float(), nullable=True),
        sa.Column('info_link', sa.String(length=500), nullable=True),
        sa.Column('list_link', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('property_auction_history', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_property_auction_history_id'), ['id'], unique=False)

    if 'property_details' not in tables:
        op.create_table('property_details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.String(length=36), nullable=False),
        sa.Column('bedrooms', sa.Integer(), nullable=True),
        sa.Column('bathrooms', sa.Float(), nullable=True),
        sa.Column('sqft', sa.Integer(), nullable=True),
        sa.Column('lot_size', sa.Float(), nullable=True),
        sa.Column('year_built', sa.Integer(), nullable=True),
        sa.Column('state_parcel_id', sa.String(length=100), nullable=True),
        sa.Column('account_number', sa.String(length=100), nullable=True),
        sa.Column('attom_id', sa.String(length=100), nullable=True),
        sa.Column('estimated_arv', sa.Float(), nullable=True),
        sa.Column('estimated_rent', sa.Float(), nullable=True),
        sa.Column('purchase_option_type', sa.String(length=100), nullable=True),
        sa.Column('total_market_value', sa.Float(), nullable=True),
        sa.Column('property_category', sa.String(length=100), nullable=True),
        sa.Column('use_code', sa.String(length=50), nullable=True),
        sa.Column('use_description', sa.String(length=255), nullable=True),
        sa.Column('zoning', sa.String(length=50), nullable=True),
        sa.Column('zoning_description', sa.String(length=255), nullable=True),
        sa.Column('legal_description', sa.Text(), nullable=True),
        sa.Column('subdivision', sa.String(length=100), nullable=True),
        sa.Column('num_stories', sa.Integer(), nullable=True),
        sa.Column('num_units', sa.Integer(), nullable=True),
        sa.Column('structure_style', sa.String(length=100), nullable=True),
        sa.Column('building_area_sqft', sa.Integer(), nullable=True),
        sa.Column('lot_acres', sa.Float(), nullable=True),
        sa.Column('assessed_value', sa.Float(), nullable=True),
        sa.Column('land_value', sa.Float(), nullable=True),
        sa.Column('improvement_value', sa.Float(), nullable=True),
        sa.Column('tax_amount', sa.Float(), nullable=True),
        sa.Column('tax_year', sa.Integer(), nullable=True),
        sa.Column('homestead_exemption', sa.Boolean(), nullable=True),
        sa.Column('last_sale_date', sa.Date(), nullable=True),
        sa.Column('last_sale_price', sa.Float(), nullable=True),
        sa.Column('last_transfer_date', sa.Date(), nullable=True),
        sa.Column('flood_zone_code', sa.String(length=20), nullable=True),
        sa.Column('is_qoz', sa.Boolean(), nullable=True),
        sa.Column('estimated_value', sa.Float(), nullable=True),
        sa.Column('rental_value', sa.Float(), nullable=True),
        sa.Column('market_value_url', sa.String(length=500), nullable=True),
        sa.Column('legal_tags', sa.String(length=500), nullable=True),
        sa.Column('appraisal_desc', sa.Text(), nullable=True),
        sa.Column('regrid_url', sa.String(length=500), nullable=True),
        sa.Column('fema_url', sa.String(length=500), nullable=True),
        sa.Column('zillow_url', sa.String(length=500), nullable=True),
        sa.Column('gsi_url', sa.String(length=500), nullable=True),
        sa.Column('gsi_data', sa.Text(), nullable=True),
        sa.Column('max_bid', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('property_id')
        )
        with op.batch_alter_table('property_details', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_property_details_id'), ['id'], unique=False)

    if 'transactions' not in tables:
        op.create_table('transactions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.String(length=36), nullable=True),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=True),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('transactions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_transactions_company_id'), ['company_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_transactions_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_index('ix_auctions_auction_date')
        batch_op.drop_index('ix_auctions_county')
        batch_op.drop_index('ix_auctions_state')

    op.drop_table('auctions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('short_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('county', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('auction_date', sa.DATE(), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tax_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('parcels_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('search_link', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('register_link', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('list_link', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('info_link', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.create_index('ix_auctions_state', ['state'], unique=False)
        batch_op.create_index('ix_auctions_county', ['county'], unique=False)
        batch_op.create_index('ix_auctions_auction_date', ['auction_date'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_property_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_company_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_details_id'))

    op.drop_table('property_details')
    with op.batch_alter_table('property_auction_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_auction_history_id'))

    op.drop_table('property_auction_history')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_property_id'))
        batch_op.drop_index(batch_op.f('ix_notes_id'))

    op.drop_table('notes')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_id'))

    op.drop_table('media')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_company_id'))

    op.drop_table('inventory_items')
    op.drop_table('expenses')
    with op.batch_alter_table('auction_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auction_details_id'))
        batch_op.drop_index(batch_op.f('ix_auction_details_case_number'))

    op.drop_table('auction_details')
    op.drop_table('user_company')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_zip_code'))
        batch_op.drop_index(batch_op.f('ix_properties_state'))
        batch_op.drop_index(batch_op.f('ix_properties_smart_tag'))
        batch_op.drop_index(batch_op.f('ix_properties_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_properties_county'))
        batch_op.drop_index(batch_op.f('ix_properties_company_id'))
        batch_op.drop_index(batch_op.f('ix_properties_city'))
        batch_op.drop_index(batch_op.f('ix_properties_auction_event_id'))

    op.drop_table('properties')
    with op.batch_alter_table('inventory_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_folders_company_id'))

    op.drop_table('inventory_folders')
    with op.batch_alter_table('auction_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auction_events_id'))

    op.drop_table('auction_events')
    # ### end Alembic commands ###
