"""add client portal auth and announcement models

Revision ID: 39933245829b
Revises: ddc93cc34101
Create Date: 2026-02-27 06:16:20.251646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39933245829b'
down_revision: Union[str, None] = 'ddc93cc34101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_announcements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_announcements_is_active'), ['is_active'], unique=False)

    op.create_table('client_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property_details.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_attachments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_attachments_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_attachments_user_id'), ['user_id'], unique=False)

    op.create_table('client_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_lists_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_lists_user_id'), ['user_id'], unique=False)

    op.create_table('client_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property_details.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_notes_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_notes_user_id'), ['user_id'], unique=False)

    op.create_table('client_list_property',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['client_lists.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property_details.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'property_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_list_property')
    with op.batch_alter_table('client_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_notes_property_id'))
        batch_op.drop_index(batch_op.f('ix_client_notes_id'))

    op.drop_table('client_notes')
    with op.batch_alter_table('client_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_lists_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_lists_id'))

    op.drop_table('client_lists')
    with op.batch_alter_table('client_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_attachments_user_id'))
        batch_op.drop_index(batch_op.f('ix_client_attachments_property_id'))
        batch_op.drop_index(batch_op.f('ix_client_attachments_id'))

    op.drop_table('client_attachments')
    with op.batch_alter_table('system_announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_announcements_is_active'))
        batch_op.drop_index(batch_op.f('ix_system_announcements_id'))

    op.drop_table('system_announcements')
    # ### end Alembic commands ###
