"""Add missing columns to auction_events from CSV

Revision ID: 4353e5c20e1a
Revises: efbfcd430aa9
Create Date: 2026-02-20 04:38:17.571949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4353e5c20e1a'
down_revision: Union[str, None] = 'efbfcd430aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tax_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('parcels_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_constraint('property_details_property_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.create_unique_constraint('property_details_property_id_key', ['property_id'])

    with op.batch_alter_table('auction_events', schema=None) as batch_op:
        batch_op.drop_column('parcels_count')
        batch_op.drop_column('tax_status')
        batch_op.drop_column('county_code')

    # ### end Alembic commands ###
