"""Phase 13 new fields

Revision ID: 442459ae973e
Revises: 99ed7fb33036
Create Date: 2026-02-09 18:36:23.578586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442459ae973e'
down_revision: Union[str, None] = '99ed7fb33036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_details', sa.Column('auction_start', sa.DateTime(), nullable=True))
    op.add_column('auction_details', sa.Column('auction_end', sa.DateTime(), nullable=True))
    op.add_column('auction_details', sa.Column('reserve_price', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('property_details', sa.Column('state_parcel_id', sa.String(length=100), nullable=True))
    op.add_column('property_details', sa.Column('account_number', sa.String(length=100), nullable=True))
    op.add_column('property_details', sa.Column('attom_id', sa.String(length=100), nullable=True))
    op.add_column('property_details', sa.Column('use_code', sa.String(length=50), nullable=True))
    op.add_column('property_details', sa.Column('use_description', sa.String(length=255), nullable=True))
    op.add_column('property_details', sa.Column('zoning', sa.String(length=50), nullable=True))
    op.add_column('property_details', sa.Column('zoning_description', sa.String(length=255), nullable=True))
    op.add_column('property_details', sa.Column('legal_description', sa.Text(), nullable=True))
    op.add_column('property_details', sa.Column('subdivision', sa.String(length=100), nullable=True))
    op.add_column('property_details', sa.Column('num_stories', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('num_units', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('structure_style', sa.String(length=100), nullable=True))
    op.add_column('property_details', sa.Column('building_area_sqft', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('lot_acres', sa.Float(), nullable=True))
    op.add_column('property_details', sa.Column('assessed_value', sa.Float(), nullable=True))
    op.add_column('property_details', sa.Column('land_value', sa.Float(), nullable=True))
    op.add_column('property_details', sa.Column('improvement_value', sa.Float(), nullable=True))
    op.add_column('property_details', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('property_details', sa.Column('tax_year', sa.Integer(), nullable=True))
    op.add_column('property_details', sa.Column('homestead_exemption', sa.Boolean(), nullable=True))
    op.add_column('property_details', sa.Column('last_sale_date', sa.Date(), nullable=True))
    op.add_column('property_details', sa.Column('last_sale_price', sa.Float(), nullable=True))
    op.add_column('property_details', sa.Column('last_transfer_date', sa.Date(), nullable=True))
    op.add_column('property_details', sa.Column('flood_zone_code', sa.String(length=20), nullable=True))
    op.add_column('property_details', sa.Column('is_qoz', sa.Boolean(), nullable=True))
    op.add_column('property_details', sa.Column('legal_tags', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_details', 'legal_tags')
    op.drop_column('property_details', 'is_qoz')
    op.drop_column('property_details', 'flood_zone_code')
    op.drop_column('property_details', 'last_transfer_date')
    op.drop_column('property_details', 'last_sale_price')
    op.drop_column('property_details', 'last_sale_date')
    op.drop_column('property_details', 'homestead_exemption')
    op.drop_column('property_details', 'tax_year')
    op.drop_column('property_details', 'tax_amount')
    op.drop_column('property_details', 'improvement_value')
    op.drop_column('property_details', 'land_value')
    op.drop_column('property_details', 'assessed_value')
    op.drop_column('property_details', 'lot_acres')
    op.drop_column('property_details', 'building_area_sqft')
    op.drop_column('property_details', 'structure_style')
    op.drop_column('property_details', 'num_units')
    op.drop_column('property_details', 'num_stories')
    op.drop_column('property_details', 'subdivision')
    op.drop_column('property_details', 'legal_description')
    op.drop_column('property_details', 'zoning_description')
    op.drop_column('property_details', 'zoning')
    op.drop_column('property_details', 'use_description')
    op.drop_column('property_details', 'use_code')
    op.drop_column('property_details', 'attom_id')
    op.drop_column('property_details', 'account_number')
    op.drop_column('property_details', 'state_parcel_id')
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    op.drop_column('auction_details', 'reserve_price')
    op.drop_column('auction_details', 'auction_end')
    op.drop_column('auction_details', 'auction_start')
    # ### end Alembic commands ###
