"""Add index to auction_date

Revision ID: 4f33a172677c
Revises: 4353e5c20e1a
Create Date: 2026-02-20 08:01:30.331989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f33a172677c'
down_revision: Union[str, None] = '4353e5c20e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auction_events_auction_date'), 'auction_events', ['auction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auction_events_auction_date'), table_name='auction_events')
    # ### end Alembic commands ###

