"""add extended property detail fields

Revision ID: 581d8a6a8424
Revises: e586f76938ee
Create Date: 2026-02-27 02:49:55.561734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581d8a6a8424'
down_revision: Union[str, None] = 'e586f76938ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternate_owner_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('state_inventory_entered_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('qoz_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('parcel_shape_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pin_ppin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('raw_parcel_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('county_fips', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('additional_parcel_numbers', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('occupancy_checked_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_column('occupancy_checked_date')
        batch_op.drop_column('additional_parcel_numbers')
        batch_op.drop_column('county_fips')
        batch_op.drop_column('raw_parcel_number')
        batch_op.drop_column('pin_ppin')
        batch_op.drop_column('parcel_shape_data')
        batch_op.drop_column('qoz_description')
        batch_op.drop_column('state_inventory_entered_date')
        batch_op.drop_column('alternate_owner_address')

    # ### end Alembic commands ###
