"""Add smart_tag and local_id

Revision ID: 618b9892104c
Revises: d534a0791b81
Create Date: 2026-02-10 01:48:39.144277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618b9892104c'
down_revision: Union[str, None] = 'd534a0791b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('smart_tag', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('local_id', sa.Integer(), autoincrement=True, nullable=True))
    op.create_index(op.f('ix_properties_smart_tag'), 'properties', ['smart_tag'], unique=True)
    op.create_unique_constraint(None, 'properties', ['local_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='unique')
    op.drop_index(op.f('ix_properties_smart_tag'), table_name='properties')
    op.drop_column('properties', 'local_id')
    op.drop_column('properties', 'smart_tag')
    # ### end Alembic commands ###
