"""add_auction_details

Revision ID: 925f1f80cca3
Revises: d72129e6ef7e
Create Date: 2026-02-09 01:13:00.122081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925f1f80cca3'
down_revision: Union[str, None] = 'd72129e6ef7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('auction_date', sa.Date(), nullable=True),
    sa.Column('scraped_file', sa.String(length=255), nullable=True),
    sa.Column('status_detail', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('sold_to', sa.String(length=255), nullable=True),
    sa.Column('auction_type', sa.String(length=100), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('opening_bid', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_index(op.f('ix_auction_details_case_number'), 'auction_details', ['case_number'], unique=False)
    op.create_index(op.f('ix_auction_details_id'), 'auction_details', ['id'], unique=False)
    op.add_column('properties', sa.Column('parcel_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_properties_parcel_id'), 'properties', ['parcel_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_parcel_id'), table_name='properties')
    op.drop_column('properties', 'parcel_id')
    op.drop_index(op.f('ix_auction_details_id'), table_name='auction_details')
    op.drop_index(op.f('ix_auction_details_case_number'), table_name='auction_details')
    op.drop_table('auction_details')
    # ### end Alembic commands ###
