"""Add full_name to users

Revision ID: 9849534c3d40
Revises: e8a7b0da15e0
Create Date: 2026-04-04 13:48:21.398864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9849534c3d40'
down_revision: Union[str, None] = 'e8a7b0da15e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_scores',
    sa.Column('parcel_id', sa.String(length=100), nullable=False),
    sa.Column('deal_score', sa.Float(), nullable=False),
    sa.Column('rating', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('score_factors', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('parcel_id'),
    sa.UniqueConstraint('parcel_id', name='uq_property_scores_parcel_id')
    )
    with op.batch_alter_table('property_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_scores_parcel_id'), ['parcel_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('property_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_scores_parcel_id'))

    op.drop_table('property_scores')
    # ### end Alembic commands ###
