"""Add locations table

Revision ID: 99ed7fb33036
Revises: 925f1f80cca3
Create Date: 2026-02-09 02:16:16.845937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ed7fb33036'
down_revision: Union[str, None] = '925f1f80cca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('fips', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('fips')
    )
    op.create_index(op.f('ix_locations_fips'), 'locations', ['fips'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_fips'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
