"""add performance indexes for property_auction_history and availability_status

Revision ID: 9b875f2af7b4
Revises: 3e1a0b3c4d5e
Create Date: 2026-03-03 23:13:50.234582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b875f2af7b4'
down_revision: Union[str, None] = '3e1a0b3c4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_auction_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_auction_history_auction_date'), ['auction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_auction_history_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_details_availability_status'), ['availability_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_details_availability_status'))

    with op.batch_alter_table('property_auction_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_auction_history_property_id'))
        batch_op.drop_index(batch_op.f('ix_property_auction_history_auction_date'))

    # ### end Alembic commands ###
