"""Add Notification and ActivityLog

Revision ID: 9f5870f6b12f
Revises: 9849534c3d40
Create Date: 2026-04-15 17:43:20.401384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5870f6b12f'
down_revision: Union[str, None] = '9849534c3d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Check existing tables
    existing_tables = inspector.get_table_names()
    
    if 'activity_logs' not in existing_tables:
        op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    if 'activity_logs' not in existing_tables:
        with op.batch_alter_table('activity_logs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_activity_logs_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    if 'notifications' not in existing_tables:
        op.create_table('notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('message', sa.String(length=500), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=True),
        sa.Column('property_id', sa.String(length=36), nullable=True),
        sa.Column('auction_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('notifications', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
            batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    auction_cols = [col['name'] for col in inspector.get_columns('auction_events')]
    with op.batch_alter_table('auction_events', schema=None) as batch_op:
        if 'available_count' not in auction_cols:
            batch_op.add_column(sa.Column('available_count', sa.Integer(), nullable=True))

    prop_cols = [col['name'] for col in inspector.get_columns('property_details')]
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        if 'owner_name' not in prop_cols:
            batch_op.add_column(sa.Column('owner_name', sa.String(length=255), nullable=True))
        if 'owner_occupied' not in prop_cols:
            batch_op.add_column(sa.Column('owner_occupied', sa.String(length=20), nullable=True))
        if 'apn_unformatted' not in prop_cols:
            batch_op.add_column(sa.Column('apn_unformatted', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_column('apn_unformatted')
        batch_op.drop_column('owner_occupied')
        batch_op.drop_column('owner_name')

    with op.batch_alter_table('auction_events', schema=None) as batch_op:
        batch_op.drop_column('available_count')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
