"""add_property_details_fields

Revision ID: a0eb2334a5b0
Revises: f102da7a6c29
Create Date: 2026-02-14 04:53:56.869450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a0eb2334a5b0'
down_revision: Union[str, None] = 'f102da7a6c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'local_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('property_details', sa.Column('appraisal_desc', sa.Text(), nullable=True))
    op.add_column('property_details', sa.Column('regrid_url', sa.String(length=500), nullable=True))
    op.add_column('property_details', sa.Column('fema_url', sa.String(length=500), nullable=True))
    op.add_column('property_details', sa.Column('zillow_url', sa.String(length=500), nullable=True))
    op.add_column('property_details', sa.Column('gsi_url', sa.String(length=500), nullable=True))
    op.add_column('property_details', sa.Column('gsi_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_details', 'gsi_data')
    op.drop_column('property_details', 'gsi_url')
    op.drop_column('property_details', 'zillow_url')
    op.drop_column('property_details', 'fema_url')
    op.drop_column('property_details', 'regrid_url')
    op.drop_column('property_details', 'appraisal_desc')
    op.alter_column('properties', 'local_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
