"""update_counties_schema

Revision ID: a3ad365993f7
Revises: bfec63e94562
Create Date: 2026-02-12 11:11:31.023601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3ad365993f7'
down_revision: Union[str, None] = 'bfec63e94562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop table first to avoid duplicate error if it exists (schema change)
    op.execute("DROP TABLE IF EXISTS counties")
    
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('county_name', sa.String(length=100), nullable=False),
    sa.Column('offices', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_code', 'county_name', name='bd_state_county_uc')
    )
    op.create_index(op.f('ix_counties_county_name'), 'counties', ['county_name'], unique=False)
    op.create_index(op.f('ix_counties_id'), 'counties', ['id'], unique=False)
    op.create_index(op.f('ix_counties_state_code'), 'counties', ['state_code'], unique=False)
    op.alter_column('properties', 'local_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'local_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_counties_state_code'), table_name='counties')
    op.drop_index(op.f('ix_counties_id'), table_name='counties')
    op.drop_index(op.f('ix_counties_county_name'), table_name='counties')
    op.drop_table('counties')
    # ### end Alembic commands ###
