"""create_counties_table

Revision ID: bfec63e94562
Revises: 21ea56ad0f10
Create Date: 2026-02-12 05:03:30.863743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfec63e94562'
down_revision: Union[str, None] = '21ea56ad0f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS counties")
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('county_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('online_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counties_county_name'), 'counties', ['county_name'], unique=False)
    op.create_index(op.f('ix_counties_id'), 'counties', ['id'], unique=False)
    op.create_index(op.f('ix_counties_state_code'), 'counties', ['state_code'], unique=False)
    # op.alter_column('properties', 'local_id',
    #            existing_type=mysql.INTEGER(),
    #            nullable=True,
    #            autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('properties', 'local_id',
    #            existing_type=mysql.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
    pass
    op.drop_index(op.f('ix_counties_state_code'), table_name='counties')
    op.drop_index(op.f('ix_counties_id'), table_name='counties')
    op.drop_index(op.f('ix_counties_county_name'), table_name='counties')
    op.drop_table('counties')
    # ### end Alembic commands ###
