"""absorb core property fields into details

Revision ID: c5de3a151c85
Revises: c7e05402635d
Create Date: 2026-02-22 00:56:59.222607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5de3a151c85'
down_revision: Union[str, None] = 'c7e05402635d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcel_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('owner_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('amount_due', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('occupancy', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cs_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('property_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_property_details_parcel_id'), ['parcel_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_details_parcel_id'))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('status')
        batch_op.drop_column('property_type')
        batch_op.drop_column('cs_number')
        batch_op.drop_column('occupancy')
        batch_op.drop_column('amount_due')
        batch_op.drop_column('description')
        batch_op.drop_column('state')
        batch_op.drop_column('county')
        batch_op.drop_column('owner_address')
        batch_op.drop_column('address')
        batch_op.drop_column('parcel_id')

    # ### end Alembic commands ###
