"""Add auction_id FK and property details columns

Revision ID: c7e05402635d
Revises: 4f33a172677c
Create Date: 2026-02-22 00:52:47.998422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e05402635d'
down_revision: Union[str, None] = '4f33a172677c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_auction_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auction_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_property_auction_history_auction_id'), ['auction_id'], unique=False)
        batch_op.create_foreign_key(None, 'auction_events', ['auction_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_category', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('purchase_option_type', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_column('purchase_option_type')
        batch_op.drop_column('property_category')

    with op.batch_alter_table('property_auction_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_property_auction_history_auction_id'))
        batch_op.drop_column('auction_id')

    # ### end Alembic commands ###
