"""add county_contacts table

Revision ID: ddc93cc34101
Revises: 581d8a6a8424
Create Date: 2026-02-27 05:19:25.845975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc93cc34101'
down_revision: Union[str, None] = '581d8a6a8424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('county_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('county_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_county_contacts_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_county_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_county_contacts_state'), ['state'], unique=False)

    # with op.batch_alter_table('auction_events', schema=None) as batch_op:
    #     batch_op.drop_index('ix_auction_events_auction_date')

    # with op.batch_alter_table('property_details', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('auction_events', schema=None) as batch_op:
        batch_op.create_index('ix_auction_events_auction_date', ['auction_date'], unique=False)

    with op.batch_alter_table('county_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_county_contacts_state'))
        batch_op.drop_index(batch_op.f('ix_county_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_county_contacts_county'))

    op.drop_table('county_contacts')
    # ### end Alembic commands ###
