"""Add expanded property fields

Revision ID: e8a7b0da15e0
Revises: 1cdbed017f3e
Create Date: 2026-03-24 07:02:25.374205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a7b0da15e0'
down_revision: Union[str, None] = '1cdbed017f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redfin_url', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('redfin_estimate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lot_sqft', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sewer_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('water_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('property_type_detail', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('import_error_msg', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('map_link', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_column('map_link')
        batch_op.drop_column('is_processed')
        batch_op.drop_column('import_error_msg')
        batch_op.drop_column('property_type_detail')
        batch_op.drop_column('water_type')
        batch_op.drop_column('sewer_type')
        batch_op.drop_column('lot_sqft')
        batch_op.drop_column('redfin_estimate')
        batch_op.drop_column('redfin_url')

    # ### end Alembic commands ###
