"""core_arch_simplification

Revision ID: efbfcd430aa9
Revises: 16d27a17105f
Create Date: 2026-02-20 02:06:18.918102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'efbfcd430aa9'
down_revision: Union[str, None] = '16d27a17105f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # We use raw SQL with CASCADE to automatically drop dependent foreign keys in Postgres.

    tables_to_drop = [
        'user_company', 'expenses', 'media', 'inventory_items',
        'transactions', 'notes', 'auction_details', 'inventory_folders',
        'properties', 'companies', 'counties', 'locations'
    ]
    
    for table in tables_to_drop:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE;")

    columns_to_drop_pd = ['total_market_value', 'estimated_rent', 'property_category', 'purchase_option_type', 'estimated_arv']
    for col in columns_to_drop_pd:
        op.execute(f"ALTER TABLE property_details DROP COLUMN IF EXISTS {col};")

    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS role;")

    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.ENUM('ADMIN', 'MANAGER', 'AGENT'), nullable=False))

    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_arv', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('purchase_option_type', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('property_category', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('estimated_rent', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_market_value', mysql.FLOAT(), nullable=True))
        batch_op.create_foreign_key('property_details_ibfk_1', 'properties', ['property_id'], ['id'])
        batch_op.create_index('property_id', ['property_id'], unique=True)

    with op.batch_alter_table('property_auction_history', schema=None) as batch_op:
        batch_op.create_foreign_key('property_auction_history_ibfk_1', 'properties', ['property_id'], ['id'])

    op.create_table('companies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', mysql.FLOAT(), nullable=True),
    sa.Column('default_bid_percentage', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='companies_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index('ix_companies_name', ['name'], unique=True)
        batch_op.create_index('ix_companies_id', ['id'], unique=False)

    op.create_table('auction_details',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('auction_date', sa.DATE(), nullable=True),
    sa.Column('auction_start', mysql.DATETIME(), nullable=True),
    sa.Column('auction_end', mysql.DATETIME(), nullable=True),
    sa.Column('reserve_price', mysql.FLOAT(), nullable=True),
    sa.Column('scraped_file', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status_detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('sold_to', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('auction_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('certificate_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('opening_bid', mysql.FLOAT(), nullable=True),
    sa.Column('raw_text', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='auction_details_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auction_details', schema=None) as batch_op:
        batch_op.create_index('property_id', ['property_id'], unique=True)
        batch_op.create_index('ix_auction_details_id', ['id'], unique=False)
        batch_op.create_index('ix_auction_details_case_number', ['case_number'], unique=False)

    op.create_table('properties',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('zip_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('county', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('property_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('parcel_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('smart_tag', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('local_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('owner_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('amount_due', mysql.FLOAT(), nullable=True),
    sa.Column('next_auction_date', sa.DATE(), nullable=True),
    sa.Column('occupancy', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tax_sale_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cs_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('parcel_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('map_link', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auction_event_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['auction_event_id'], ['auction_events.id'], name='properties_ibfk_1'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='properties_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index('local_id', ['local_id'], unique=True)
        batch_op.create_index('ix_properties_zip_code', ['zip_code'], unique=False)
        batch_op.create_index('ix_properties_state', ['state'], unique=False)
        batch_op.create_index('ix_properties_smart_tag', ['smart_tag'], unique=True)
        batch_op.create_index('ix_properties_parcel_id', ['parcel_id'], unique=True)
        batch_op.create_index('ix_properties_county', ['county'], unique=False)
        batch_op.create_index('ix_properties_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_properties_city', ['city'], unique=False)
        batch_op.create_index('ix_properties_auction_event_id', ['auction_event_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='notes_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notes_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_property_id', ['property_id'], unique=False)
        batch_op.create_index('ix_notes_id', ['id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('property_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='transactions_ibfk_1'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='transactions_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_property_id', ['property_id'], unique=False)
        batch_op.create_index('ix_transactions_company_id', ['company_id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('folder_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('property_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('user_notes', mysql.TEXT(), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='inventory_items_ibfk_1'),
    sa.ForeignKeyConstraint(['folder_id'], ['inventory_folders.id'], name='inventory_items_ibfk_2'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='inventory_items_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_items_company_id', ['company_id'], unique=False)

    op.create_table('locations',
    sa.Column('fips', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('fips'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('ix_locations_fips', ['fips'], unique=False)

    op.create_table('counties',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state_code', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('county_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('offices', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('counties', schema=None) as batch_op:
        batch_op.create_index('ix_counties_state_code', ['state_code'], unique=False)
        batch_op.create_index('ix_counties_id', ['id'], unique=False)
        batch_op.create_index('ix_counties_county_name', ['county_name'], unique=False)
        batch_op.create_index('bd_state_county_uc', ['state_code', 'county_name'], unique=True)

    op.create_table('inventory_folders',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('parent_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_system', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='inventory_folders_ibfk_1'),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory_folders.id'], name='inventory_folders_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('inventory_folders', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_folders_company_id', ['company_id'], unique=False)

    op.create_table('media',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('property_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('media_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('is_primary', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='media_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index('ix_media_id', ['id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('property_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='expenses_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_company',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='user_company_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_company_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'company_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
