"""Add User Roles and Companies

Revision ID: f102da7a6c29
Revises: 088730af03b3
Create Date: 2026-02-14 04:16:35.820703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f102da7a6c29'
down_revision: Union[str, None] = '088730af03b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('user_company',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    op.add_column('properties', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('properties', 'local_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('ix_properties_company_id'), 'properties', ['company_id'], unique=False)
    op.create_foreign_key(None, 'properties', 'companies', ['company_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'MANAGER', 'AGENT', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MANAGER', 'AGENT', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_company_id'), table_name='properties')
    op.alter_column('properties', 'local_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('properties', 'company_id')
    op.drop_table('user_company')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
