"""add_property_availability

Revision ID: f592373c8447
Revises: 2eeea9bf3e3e
Create Date: 2026-02-26 07:36:06.911161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f592373c8447'
down_revision: Union[str, None] = '2eeea9bf3e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_availability_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('change_source', sa.String(length=100), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_availability_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_availability_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_availability_history_property_id'), ['property_id'], unique=False)

    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.drop_column('availability_status')

    with op.batch_alter_table('property_availability_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_availability_history_property_id'))
        batch_op.drop_index(batch_op.f('ix_property_availability_history_id'))

    op.drop_table('property_availability_history')
    # ### end Alembic commands ###
